Tg 677 ultimi interventi rinnovi vita online e rimessa
wopta/goworkspace pull request #297
Opened 2024-11-12 11:40 UTC by fpittoni

2024-11-12 13:03 UTC, diogo-wopta commented on companydata/life-in-axa.go
> +		}
let's simplify the flow
```golang
payment := models.FabrickPaymentProvider
if flow == models.RemittanceMgaFlow {
    payment = models.ManualPaymentProvider
}
```

2024-11-13 10:30 UTC, diogo-wopta approved these changes

2024-11-15 11:29 UTC, Yousef-Hammar requested changes

2024-11-15 11:29 UTC, Yousef-Hammar commented on payment/common/utils.go
> +}
As I've anticipated in our call, I would change this function according to these steps:

`1. check if policy channel is network
     a. if so, get node info (node+warrant)
     b. check if input provider is compatible with node flow
         - if not, error
  2. set policy provider to input provider        
`

2024-11-18 12:01 UTC, diogo-wopta approved these changes

2024-11-18 12:03 UTC, Yousef-Hammar approved these changes

2024-11-19 08:38 UTC, merged