Vehicle model
wopta/goworkspace pull request #55
Opened 2023-06-19 14:42 UTC by pierlucatonioloreply

2023-06-20 09:44 UTC, Yousef-Hammar requested changes

2023-06-20 09:44 UTC, Yousef-Hammar commented on models/vehicle.go
> +}
In bigquery tags replace variable name with `-`

2023-06-20 09:44 UTC, Yousef-Hammar commented on .gitignore
> +lib/file-utils.go
Remove `lib/file-utiles.go` entry

2023-06-20 12:40 UTC, diogo-wopta commented on models/vehicle.go
> +	RegistrationDate        string `firestore:"registrationDate" json:"registrationDate,omitempty" bigquery:"registrationDate"`
`RegistrationDate` should be of type `time.Time`

2023-06-20 12:40 UTC, diogo-wopta commented on models/vehicle.go
> +	BodyType                string `firestore:"bodytype" json:"bodytype,omitempty" bigquery:"bodytype"`
Non-standard PascalCase/camelCase:

```
BodyType                string `firestore:"bodyType" json:"bodyType,omitempty" bigquery:"-"`
```

2023-06-20 12:40 UTC, diogo-wopta commented on models/vehicle.go
> +	TowHosokPresence        bool   `firestore:"towHosokPresence" json:"towHosokPresence,omitempty" bigquery:"towHosokPresence"`
Typo on towHook
```
HasTowHook        bool   `firestore:"hasTowHook" json:"hasTowHook,omitempty" bigquery:"-"`
```

2023-06-20 12:40 UTC, diogo-wopta commented on models/vehicle.go
> +	AlreadyOwner            string `firestore:"alreadyOwner" json:"alreadyOwner,omitempty" bigquery:"alreadyOwner"`
@Yousef-Hammar @nahidalgo maybe rename in `OwnershipStatus`? `AlreadyOwner` seems like it would be a `bool` but it's actually an enum.

2023-06-20 12:40 UTC, diogo-wopta commented on models/vehicle.go
> +	OwnerNumber             uint   `firestore:"ownerNumber" json:"ownerNumber,omitempty" bigquery:"ownerNumber"`
If the field refers to the quantity/number of owners rename in:
```
NumberOfOwners             uint   `firestore:"numberOfOwners" json:"numberOfOwners,omitempty" bigquery:"-"`
```

2023-06-20 12:40 UTC, diogo-wopta commented on models/vehicle.go
> +}
Change `uint` in `int64`

2023-06-22 13:20 UTC, nahidalgo requested changes, later dismissed

2023-06-22 13:20 UTC, nahidalgo commented on models/vehicle.go
> +	HasTowHook              bool      `firestore:"hasTowHook" json:"hasTwoHook,omitempty" bigquery:"-"`
Still a typo here, in the json tag
```suggestion
	HasTowHook              bool      `firestore:"hasTowHook" json:"hasTowHook,omitempty" bigquery:"-"`
```

2023-06-23 07:44 UTC, diogo-wopta approved these changes

2023-06-23 07:51 UTC, Yousef-Hammar approved these changes

2023-06-23 07:52 UTC, Yousef-Hammar approved these changes

2023-06-23 07:52 UTC, diogo-wopta approved these changes

2023-06-23 07:54 UTC, diogo-wopta approved these changes

2023-06-23 07:56 UTC, merged