Wb 376
wopta/goworkspace pull request #58
Opened 2023-06-22 12:44 UTC by pierlucatonioloreply

2023-06-22 13:13 UTC, nahidalgo requested changes

2023-06-22 13:13 UTC, nahidalgo commented on user/get-users.go
> +}
This is equal to the `GetPoliciesReq`. I think there should be create a Query struct inside model function. What do you think @Yousef-Hammar  @diogo-wopta

2023-06-22 13:13 UTC, nahidalgo commented on user/get-users.go
> +}
Add these structs on the top of the file

2023-06-22 13:13 UTC, nahidalgo commented on user/user.go
> +				Route:   "/user/v1",
The domain already has user, so you can leave only `v1`
```suggestion
				Route:   "/v1",
```

2023-06-22 13:15 UTC, nahidalgo submitted a review, later dismissed

2023-06-22 13:15 UTC, nahidalgo commented on user/user.go
> +				Roles:   []string{models.UserRoleAll},
Here, the role should be `models.UserRoleAdmin`

2023-06-23 07:28 UTC, Yousef-Hammar approved these changes

2023-06-23 07:29 UTC, diogo-wopta approved these changes

2023-06-23 07:31 UTC, diogo-wopta approved these changes

2023-06-23 07:35 UTC, merged