added quotation api
wopta/goworkspace pull request #66
Opened 2023-07-05 06:27 UTC by pierlucatonioloreply

body used to test:

{
    "id": null,
    "idSign": null,
    "idPay": null,
    "contractFileId": null,
    "uid": null,
    "productUid": null,
    "productVersion": "v1",
    "proposalNumber": null,
    "number": null,
    "numberCompany": null,
    "status": null,
    "company": "axa",
    "name": "life",
    "nameDesc": "Wopta per te Gap",
    "startDate": "2023-05-12T15:37:14.009Z",
    "endDate": "2028-05-12T15:37:14.009Z",
    "creationDate": "0001-01-01T00:00:00.000Z",
    "updated": "0001-01-01T00:00:00.000Z",
    "payment": null,
    "paymentType": null,
    "paymentSplit": null,
    "isPay": null,
    "isAutoRenew": null,
    "isSign": null,
    "coverageType": null,
    "voucher": null,
    "channel": null,
    "covenant": null,
    "taxAmount": null,
    "priceNett": null,
    "priceGross": null,
    "priceNettMonthly": null,
    "priceGrossMonthly": null,
    "quoteQuestions": null,
    "contractor": {},
    "assets": [
        {
            "name": "gap",
            "address": "Via Carlo Vidua 17",
            "type": "vehicleType",
            "building": null,
            "person": {
                "residence": {
                    "locality": "VI"
                }
            },
            "enterprise": null,
            "isContractor": false,
            "guarantees": null,
            "vehicle": {
                "plate": "AA111AA",
                "manufacturer": "Opel",
                "registrationDate": "2023-05-12T15:37:14.009Z",
                "ownershipStatus": "si",
                "numberOfOwners": 1,
                "priceValue": 40000,
                "vehicleType": "car",
                "weight": "1302",
                "powerSupply": "benzina",
                "hasSatellite": false
            }
        }
    ],
    "attachments": [],
    "statements": [],
    "surveys": [],
    "offersPrices": {
        "default": {
            "yearly": {
                "net": 15.93,
                "tax": 0,
                "gross": 15.93,
                "delta": 0,
                "discount": 0
            }
        }
    },
    "offerName": null,
    "codeCompany": null
}

2023-07-05 09:03 UTC, diogo-wopta commented on quote/gap.go
> +	req := lib.ErrorByte(io.ReadAll(r.Body))
Add logging for handler start.
log.Println("[GapFx] Handler start")

2023-07-05 09:04 UTC, diogo-wopta commented on quote/gap.go
> +	res, e := Gap(authToken.Role, data)
Why are we passing the user role if it's not being used?

2023-07-05 09:05 UTC, diogo-wopta commented on quote/gap.go
> +	e := json.Unmarshal(req, &data)
Handle error with lib.CheckError(e)

2023-07-05 09:07 UTC, diogo-wopta commented on quote/gap.go
> +	res, e := Gap(authToken.Role, data)
We are not handling the error, but seeing the Gap function the error is never set internally.

2023-07-05 09:08 UTC, diogo-wopta commented on quote/gap.go
> +	fmt.Printf("valore base e' %d\n", duration)
use the log library with english messages

2023-07-05 09:11 UTC, diogo-wopta commented on quote/gap.go
> +func Gap(role string, data models.Policy) (models.Policy, error) {
We could pass the policy (data) as a pointer as to modify incrementally the same object (this is also valid for the function setOfferPrices)

2023-07-05 09:13 UTC, diogo-wopta commented on quote/gap.go
> +		},
we could extract the construction of an offer price into a function (the only difference is the multiplier) that internally do all the math for calculating Net, Tax and Gross values

2023-07-05 09:14 UTC, diogo-wopta commented on quote/gap.go
> +		//fmt.Println(row)
remove commented code

2023-07-06 10:17 UTC, Yousef-Hammar requested changes

2023-07-06 10:17 UTC, Yousef-Hammar commented on quote/gap.go
> +
add check if residence area is equal to empty string and call checkerror

2023-07-06 10:17 UTC, Yousef-Hammar commented on quote/gap.go
> +	//get the residence area
add log saying get area using standard format (e.g., [GAP] )

2023-07-06 10:17 UTC, Yousef-Hammar commented on quote/gap.go
> +	log.Printf("valore completo veicolo*tax e' %f\n", completeGapMultiplierFloat*float64(vehicleValue))
remove these two logs

2023-07-06 10:17 UTC, Yousef-Hammar commented on quote/gap.go
> +	log.Printf("valore completo e' %f\n", completeGapMultiplierFloat)
change message with baseMultiplier and completeMultiplier

2023-07-06 10:17 UTC, Yousef-Hammar commented on quote/gap.go
> +}
remove this

2023-07-06 10:17 UTC, Yousef-Hammar commented on quote/gap.go
> +	baseGapMultiplierFloat, completeGapMultiplierFloat := getGapMultipliers(baseMatrixDF, completeMatrixDF, duration, residenceArea)
insert multipliers in a map[string]float64 where the key if the offerName (e.g., base/complete) and the value will be the multiplier.
Use this map inside the function setOfferPrices

2023-07-06 10:17 UTC, Yousef-Hammar commented on quote/gap.go
> +func setOffersPrices(data *models.Policy, vehicleValue int64, baseGapMultiplierFloat float64, completeGapMultiplierFloat float64) {
input to this function (data *models.Policy, vehicleValue int64, multipliers map[string]float64)
use a for loop to set the prices for each offer

2023-07-11 09:24 UTC, closed without merging