[WIP] Gap sellable quote integration
wopta/goworkspace pull request #71
Opened 2023-07-06 17:11 UTC by ruixuan-xu

The Pull request is not tested yet.
The logic for tax is still not functioning as there are some doubts on the requirements.

2023-07-07 09:23 UTC, Yousef-Hammar requested changes

2023-07-07 09:23 UTC, Yousef-Hammar commented on quote/gap.go
> +	return string(policyJson), nil, err
return also the policy

2023-07-07 09:23 UTC, Yousef-Hammar commented on quote/gap.go
> +	csvFile := lib.GetFilesByEnv("quote/gap_matrix_base.csv")
you are not using the path variable, so you will read always the same file

2023-07-07 09:23 UTC, Yousef-Hammar commented on quote/gap.go
> +	guarantees := make([]models.Guarante, 0, 10)
change with `make([]models.Guarante, 0)`

2023-07-07 09:23 UTC, Yousef-Hammar commented on quote/gap.go
> +			Gross:    grossPrice,
round prices here

2023-07-07 09:23 UTC, Yousef-Hammar commented on quote/gap.go
> +	TaxOnPrice := netPrice * (tax / 100)
first letter lower case

2023-07-07 09:23 UTC, Yousef-Hammar commented on models/vehicle.go
> +	State              string    `firestore:"state,omitempty"              json:"state,omitempty"              bigquery:"-"` // VEICOLO NUOVO, USATO, ETC...
change `State` into `Condition`

2023-07-07 09:23 UTC, Yousef-Hammar commented on quote/gap.go
> +func Gap(role string, p *models.Policy) {
GENERAL: do not use single letter names for variables (e.g., p -> policy/data)

2023-07-07 09:23 UTC, Yousef-Hammar commented on quote/gap.go
> +	for _, g := range product.Companies[0].GuaranteesMap {
do not use single letter names for variable names

2023-07-07 09:23 UTC, Yousef-Hammar commented on quote/gap.go
> +	}
change into map[string]string where the key is the offerName and the value is the path to matrix file

2023-07-07 09:23 UTC, Yousef-Hammar commented on quote/gap.go
> +	p.Assets[0].Guarantees = guarantees
put into a separate function called `initGuarantees`

2023-07-07 09:23 UTC, Yousef-Hammar commented on quote/gap.go
> +
put this into a function named `getTaxValue`

2023-07-07 09:23 UTC, Yousef-Hammar commented on quote/gap.go
> +	residenceCode := p.Assets[0].Person.Residence.Locality
province is in `CityCode` field

2023-07-07 09:23 UTC, Yousef-Hammar commented on quote/gap.go
> +}
remove this function and move the rounding to `calculateOfferPrices` function

2023-07-07 09:23 UTC, Yousef-Hammar commented on quote/gap.go
> +}
1. change name into `calculateOfferPrices`
2. remove `vehiclePrice` input, you already have it inside policy object
3. remove `tax` input, you will call the function `getTaxValue`
4. remove `gapMultipliers` input, you will call the function `getMultipliers`

2023-07-07 09:23 UTC, Yousef-Hammar commented on quote/gap.go
> +}
1. change the name into `getMultipliers`
2. move here the map that contains csv paths

this function will take in input also the offerName and return the multipliers for that offer

2023-07-07 09:23 UTC, Yousef-Hammar commented on sellable/sellable.go
> +			},
we don't need and enpoint for GAP

2023-07-07 09:23 UTC, Yousef-Hammar commented on sellable/vehicle.go
> +}
we don't need this, you can remove it

2023-07-07 09:23 UTC, Yousef-Hammar commented on sellable/vehicle.go
> +func productForVehicle(p *models.Policy, r string) (models.Product, error) {
change name into `getProduct`

2023-07-11 11:41 UTC, diogo-wopta approved these changes

2023-07-11 13:07 UTC, Yousef-Hammar approved these changes

2023-07-11 13:07 UTC, Yousef-Hammar commented on quote/gap.go
> +	policy.Company = product.Companies[0].Name
not required

2023-07-11 13:07 UTC, merged