refactoring send email
wopta/goworkspace pull request #83
Opened 2023-07-24 16:04 UTC by pierlucatonioloreply

2023-07-25 16:00 UTC, Yousef-Hammar requested changes

2023-07-25 16:00 UTC, Yousef-Hammar commented on mail/mail-policy.go
> +// }
remove comment

2023-07-25 16:00 UTC, Yousef-Hammar commented on mail/mail-policy.go
> +// }
remove comment

2023-07-25 16:00 UTC, Yousef-Hammar commented on mail/send.go
> +		headers["Cc"] = "pierluca1992@gmail.com; " + obj.Cc
remove your email

2023-07-25 16:00 UTC, Yousef-Hammar commented on mail/send.go
> +		// }
remove comments

2023-07-25 16:00 UTC, Yousef-Hammar commented on mail/mail-utils.go
> +		}
use function `GetFilesByEnv` that you can find in `lib` folder to read the file

2023-07-25 16:00 UTC, Yousef-Hammar commented on mail/mail-utils.go
> +	}
use function `GetFilesByEnv` that you can find in `lib` folder to read the file

2023-07-25 16:00 UTC, Yousef-Hammar commented on mail/mail-utils.go
> +		bodyData.ProductName = "GAP"
productName is not `GAP` but `Auto Valore Protetto`

2023-07-25 16:00 UTC, Yousef-Hammar commented on mail/mail-utils.go
> +
don't use variables just check value inside policy

2023-07-25 16:00 UTC, Yousef-Hammar commented on mail/mail-utils.go
> +func CheckChannel(policy *models.Policy) string {
rename function into `getChannel`.
In general this utils functions are not needed outside this domain so I think it's better to have the function name starting with lower case letter

2023-07-25 16:00 UTC, Yousef-Hammar commented on mail/mail-policy.go
> +// }
remove comments

2023-07-27 08:38 UTC, Yousef-Hammar commented on payment/manual.go
>  		Name: policy.Contractor.Name + "_" + policy.Contractor.Surname + "_" +
Change this into 
`Name: strings.ReplaceAll(policy.Contractor.Name + " " + policy.Contractor.Surname + " " + policy.NameDesc, " ", "_") + "_contratto.pdf",`

2023-07-27 08:40 UTC, Yousef-Hammar commented on mail/mail-utils.go
> +
remove empty line

2023-07-27 08:40 UTC, Yousef-Hammar commented on mail/mail-utils.go
> +
remove empty line

2023-07-27 08:40 UTC, Yousef-Hammar commented on mail/mail-policy.go
> +
remove empty line

2023-07-28 07:58 UTC, Yousef-Hammar requested changes

2023-07-28 07:58 UTC, Yousef-Hammar commented on mail/mail-policy.go
> +	templateFile := getTemplateByChannel(policy, "sign")
template is `sign` or should be another value?
In general create constants at the beginning of the file with these values

2023-08-01 10:28 UTC, diogo-wopta approved these changes

2023-08-01 10:29 UTC, Yousef-Hammar approved these changes

2023-08-01 10:30 UTC, merged